### PR TITLE
ryebread-n-cheese

### PR DESCRIPTION
**Pull request by KasperFischer**
I would like to merge my awesome recipe!

### CODE REVIEW

**Review by ThildeBT — CHANGES_REQUESTED** [review]
Hi Kasper, 

It looks good, but maybe it could need something green. Add it to your recipe and I think it is ready to merge :-)

**Comment by KasperFischer** [comment]
Lettuce!

**Review by ThildeBT — APPROVED** [review]
Hi Kasper,
Looks good, I will approve it and close the issue.

**Comment by ThildeBT** [comment]
Merge with lettuce accepted.

**Pull request merged**
