### PR TITLE
Fix  issue: No capital letters in milk recipe #20 

### PR DESCRIPTION
**Pull request by Whynotmemate**
Fix  issue: No capital letters in milk recipe #20 
This updated version of the Milk recipe resolves the lower case letters at the start of the sentences.

### CODE REVIEW

**Comment by ThildeBT** [comment]
Great pull request message, maaaybbe you could add something the the milk recipe, it is a little boring. Please do that and add, commit and push again!

**Comment by Whynotmemate** [comment]
I have updated the changes to so that there are added speces to the milk ingredients and also an advanced recipe has been added.

**Comment by ThildeBT** [comment]
Great, thanks for the additions, much needed, pull request accepted!

**Comment by ThildeBT** [comment]
issues #20 and #27 resolved

**Pull request merged**
